;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	counsel-M-x
	forward-sexp
	kill-region
	lsp-signature-toggle-full-docs
	mark-sexp
	markdown-beginning-of-line
	markdown-end-of-line
	markdown-outdent-or-delete
	))

(setq mc/cmds-to-run-once
      '(
	yank-rectangle
	))
