.\" Manpage for git-bclean
.TH GIT_BCLEAN 1 "September 05 2024" "Git 2.45.1" "Git Manual"
.SH NAME
git-bclean \- Delete all branches which have no remote version
.SH SYNOPSIS
\fIgit bclean\fR [OPTIONS]
.SH DESCRIPTION
Deletes all branches which have no remote version.
.SH OPTIONS
\-h
.RS 4
Show a help message and exit
.SH SEE ALSO
git-branch(1)
.SH BUGS
No known bugs.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
